### ISSUE TITLE
Issue getting lambda function to work

### ISSUE THREAD

**Issue by daveyman123** [just4give/raspi-dexter-lambda#2] opened 2018-03-17 22:39 UTC
Hey, its bob dylan from Youtube.

I am still struggling getting the bot to work.

I am getting this error whenever i wake the robot:
{ DependencyFailedException: Invalid Lambda Response: Received error response from Lambda: Unhandled
    at Object.extractError (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/protocol/json.js:48:27)

I have followed the tutorials to a T and am still having trouble understanding if maybe it is a permissions issue? or maybe it could be something to do with sns(as i havent configured the text message capabilities and have tried to remove them from the handler.js)

please help! lol

**Comment by daveyman123** [comment] 2018-03-17 22:45
I should say: I am sorry if this is the wrong place to be posting this.

also, Nice touch adding different responses depending on the time of day :)

**Comment by just4give** [comment] 2018-03-18 12:56
Hi there, you are at right place :) I am wondering about the error you are getting on your pi. Can you please check if you are running 6.x nodejs version on your pi. And add some console.log inside bot.js file ( https://github.com/just4give/raspi-dexter-lex-ai.git) . There is a function called record() which will be invoked by the python program when wake word is detected.

**Comment by daveyman123** [comment] 2018-03-18 14:15
bot.js runs fine. I will try to add a console.log. Nodejs -v returns 4.8.0. I will try to upgrade. I have tried hardcoding the raspberry pi address as seen here:
https://gyazo.com/47d1640c681ebb2a87a216c71817f9e9

**Comment by daveyman123** [comment] 2018-03-18 14:56
here is the output from running bot.js:
` retryDelay: 50.995956786013316 } 'DependencyFailedException: Invalid Lambda Response: Received error response from Lambda: Unhandled\n    at Object.extractError (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/protocol/json.js:48:27)\n    at Request.extractError (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)\n    at Request.callListeners (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/pi/raspi-dexter-lex-ai/node_modules/aws-sdk/lib/request.js:685:12)'`

**Comment by just4give** [comment] 2018-03-18 15:44
DependencyFailedException could be thrown for few different issues. Take a look at this link https://docs.aws.amazon.com/pt_br/lex/latest/dg/API_PostText.html

1. check if your user has permission to lex , sns, lambda and s3
2. change the lambda time out as this might take longer than 5 seconds.

<img width="1167" alt="screen shot 2018-03-18 at 11 41 13 am" src="https://user-images.githubusercontent.com/9275193/37567726-4f59e2f0-2aa1-11e8-8ee5-4a27d75015b3.png">

**Comment by daveyman123** [comment] 2018-03-18 16:28
https://gyazo.com/ca7082a8580904cf77b32e3f0ca07518
I have provided all these permissions but it still gives me the error permission denied

I can upload a picture to my s3 bucket using AWS CLI

EDIT:
I fixed the permission issue now I am back to getting the dependencyfailedexception error. I will work on it more

**Comment by daveyman123** [comment] 2018-03-18 17:10
its not creating a console.log from bot.js so it must not be getting to that step in the code.

**Comment by just4give** [comment] 2018-03-18 18:10
as you are getting error from raspi-dexter-lex-ai , definitely python code is calling bot.js when wake word is detected.  Add console.log before the line
```
lexruntime.postContent(params, function(err, data) 
``` 
this code actually converts the request.wav ( the recorded voice) into input stream and pass to lex api.  Also check the timeout of your lambda function. Set it to a high value like 2 minutes. 

Also check the log of your raspi-image-server's server.js ... If the lex api was called , your lambda function should be invoked which should call /api/capture of your raspi-image-server 

Also check the cloudwatch log of your lambda function on aws console.

**Comment by just4give** [comment] 2018-03-18 18:12
I am sure you have changed the lex bot name with yours...in case you did not , please modify that too
```
var params = {
     botAlias: '$LATEST',
     botName: 'FaceDetectorAI',
     userId: 'lexHeadTesting',
     contentType: 'audio/l16; rate=16000; channels=1',
     inputStream: inputStream
   };
```

**Comment by daveyman123** [comment] 2018-03-18 18:32
Thank you for helping me troubleshoot. I am taking a break but will be home soon to try these suggestions

**Comment by daveyman123** [comment] 2018-03-19 17:40
I have made some progress. It seems I wasnt installing the packages that I needed for lambda function to run. Also I had a different name for my lambda function which I needed to change in serverless.yml

npm install request
npm install aws-sdk
npm install moment-timezone

Thank you again for your help so far. I am stuck again however, the console.log says photo captured but nothing appears in my bucket. I will keep working on it later today :)

**Comment by daveyman123** [comment] 2018-03-20 15:50
I am having trouble with credentials when it comes to uploading a photo to my bucket. Do I need to add an s3 trigger in the lambda function?

I get the following error:
 message: 'Missing credentials in config'

however, something is updating in my s3 bucket when I run the program:
https://gyazo.com/706a9920d05d17dd78635d789ef7d0d5

Do I need to set up sns or a dynamoDB?

Do you have a patreon, paypal, or bitcoin address I can donate to, Mithun?

**Comment by just4give** [comment] 2018-03-20 17:59
I am guessing you are getting error from this [code ](https://github.com/just4give/raspi-image-server/blob/master/upload-s3.js#L17) ?  If yes, did you configure aws cli on your pi ? 

For text message to your phone, you need to configure SNS topic and update the ARN 

![image](https://user-images.githubusercontent.com/9275193/37673577-f3bf0824-2c46-11e8-8ced-a224a85d6cd3.png)


![image](https://user-images.githubusercontent.com/9275193/37673756-6ac14716-2c47-11e8-9c10-60d1a523dcda.png)

**Comment by daveyman123** [comment] 2018-03-20 18:02
Ok ok. I will configure SNS topic and update the ARN.

I have configured cli on my pi and can upload a picture using that.

**Comment by just4give** [comment] 2018-03-20 18:05
Also make sure you are using right region...

**Comment by daveyman123** [comment] 2018-03-20 18:08
Ok apparently though S3 does not require region specification as it is global:
 
"S3 does not require region selection."

**Comment by just4give** [comment] 2018-03-20 18:12
That's right but code updates the region and sometime back I had some issue when I had different region in node sdk compared to what I configured in aws cli ... worth checking again ..... also your screenshot shows some folder created in s3 but my code only uploads jpg file... image will be captured under photos subfolder where your image server is running.

**Comment by daveyman123** [comment] 2018-03-20 18:13
yes the image is created in photos subdirectory. However, no matter what bucket I use it doesnt upload just the jpg. I will keep looking into it 👍

**Comment by just4give** [comment] 2018-03-20 18:14
You may update https://github.com/just4give/raspi-image-server/blob/master/config.json  to match your region with your aws cli as you were able to call aws cli s3 cp successfully

**Comment by daveyman123** [comment] 2018-03-20 18:17
"awsRegion":"us-east-1", <--This is my region also
  "s3Bucket":"raspberrypijohnypie",
  "lexVoiceId":"Justin",

Im not sure what this is below:
  "awsFaceCollection":"raspifacecollection"

**Comment by just4give** [comment] 2018-03-20 18:18
You may try to clone this file https://github.com/just4give/raspi-image-server/blob/master/upload-s3.js  and try to upload existing jpg to s3 using nodejs sdk... this will help you reduce some debug time without involving lex and camera

**Comment by just4give** [comment] 2018-03-20 18:19
raspifacecollection is irrelevant while uploading .... it's needed by your lambda ..you can just keep it there

**Comment by daveyman123** [comment] 2018-03-20 18:32
for some reason my lambda function is timing out after 30 seconds so that could be the cause of why its not uploading the image:
https://gyazo.com/5761d32beab232341dd7cf7f0ce32009

I have also set up SNS and pasted the ARN topic into the handler.js

**Comment by just4give** [comment] 2018-03-20 19:46
try to increase your lambda timeout to 2m

<img width="1167" alt="screen shot 2018-03-18 at 11 41 13 am" src="https://user-images.githubusercontent.com/9275193/37567726-4f59e2f0-2aa1-11e8-8ee5-4a27d75015b3.png">

**Comment by daveyman123** [comment] 2018-03-21 17:31
I started over with a new raspi image and new aws account. I am still getting the error:
Invalid Bot Configuration: Lambda request did not complete within permissible time (30 seconds).

I think it has something to do with permissions to my s3 bucket?

**Comment by just4give** [comment] 2018-03-22 03:00
You mean you are getting time out after 30s event after setting timeout to 2 minutes as I requested?

**Comment by daveyman123** [comment] 2018-03-22 03:31
Yes lambda is set to 2 min

**Comment by just4give** [comment] 2018-03-22 12:20
Then I would suggest you to take one step at a time. Try to call the capture API http://pi-ip:80/api/capture through postman passing Basic Authorization as raspi:secret and see if that captures  jpg and upload to your s3 bucket. This is independent of lambda function. On success your jpg should be uploaded to s3 bucket and in response you should see the s3 key. See the image-server log in case of failure. This is step works, next thing we can debug is the lambda.

**Comment by daveyman123** [comment] 2018-03-22 12:22
Okay I'll give it a shot 👍

**Comment by daveyman123** [comment] 2018-03-22 13:57
Here is my output for my server after sending a post request and waiting about 10 min:
```
Magic happens on port 80
filename 1521726324572.jpg
photo captured
{ Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
  message: 'Missing credentials in config',
  errno: 'ETIMEDOUT',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2018-03-22T13:47:39.758Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     errno: 'ETIMEDOUT',
     code: 'CredentialsError',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2018-03-22T13:47:39.757Z,
     originalError:
      { errno: 'ETIMEDOUT',
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,



```
Here is my config file:
```
{
  "awsRegion":"us-east-1",
  "s3Bucket":"daveyman123",
  "lexVoiceId":"Justin",
  "awsFaceCollection":"raspifacecollection"
}






```

I am not sure how to check the logs of the server. My s3 bucket is set to public ("daveyman123" is the name) and there are no uploaded photos in it.

**Comment by just4give** [comment] 2018-03-22 15:35
So clearly aws-sdk could not load credential you have configured using aws cli. As you are running image server as sudo, you need to configure aws cli using sodo 
```
sudo aws configure
```
Alternatively you can pass hard coded credential inside upload-s3.js (line #3 ) as 
```
AWS.config.update({
  accessKeyId: 'asdjsadkskdskskdk',
  secretAccessKey: 'sdsadsissdiidicdsi',
  region: 'us-east-1'
});
```
Then call the api one more time and see what happens....

**Comment by daveyman123** [comment] 2018-03-22 15:50
i needed to have my credentials as Sudo. Thank you so much

**Comment by daveyman123** [comment] 2018-03-22 15:55
Now its just saying it "cant see any face" I have not set up sns yet. I will keep at it.

Thanks again for your help, Mithun. This project is great!

**Comment by just4give** [comment] 2018-03-22 16:11
Cool... so you are able to see images uploaded to S2. "cant see any face" is an error message when Rekognition api can't see any face in the uploaded image. Just view the image uploaded to S3...may be the image does not have any visible human face. Your face should be in front of the camera so that captured image has your face.

**Comment by daveyman123** [comment] 2018-03-22 16:19
ive tried almost 10 photos with good lighting. maybe I should change the threshold or something?

message: 'The collection id: raspifacecollection does not exist',

**Comment by just4give** [comment] 2018-03-22 16:31
do you see human face on the captured images? Based on the image you can determine where you face should be when Pi takes your photo :)

**Comment by daveyman123** [comment] 2018-03-22 16:43
I will keep working at it. I have tried like 2 dozen photos though lol. there is no box around my face or any indication of being human

**Comment by just4give** [comment] 2018-03-22 18:57
I am not creating box around face. Try to play with those uploaded image on aws web console and see if it's able to match your face with a source image of yours....

**Comment by daveyman123** [comment] 2018-03-22 19:25
I played with it a little bit and it says 93 percent similarity in detection

**Comment by just4give** [comment] 2018-03-22 19:48
in that case you should not see "can't see any faces"

**Comment by just4give** [comment] 2018-03-23 01:12
If you like to support me ..here is paypal link -> paypal.me/rmohanta404   
Thank you !

**Comment by daveyman123** [comment] 2018-03-23 02:08
ok I sent you 25 dollars now because if I were to wait until I finished the
robot, I would probably forget lol

**Comment by just4give** [comment] 2018-03-23 03:41
Thank you very much for your generous donation. I really appreciate it...

**Comment by daveyman123** [comment] 2018-03-23 13:04
Yup no problem. Theres more where that came from.

How do I go about troubleshooting this issue with s3recognition?

**Comment by just4give** [comment] 2018-03-23 13:50
So you are still seeing "Can't see any faces" ? In that case I would request you to run search-faces.js manually on your pi. Also other day I told you collectionId is not need but I was wrong. Actually I am using that inside search-faces.js (https://github.com/just4give/raspi-image-server/blob/master/search-faces.js#L11)

Once your jpg is uploaded in s3 , get the filename from console log and pass that to search-faces.js and see how that works. Also check the file content in s3 console to make sure image has a face.

**Comment by daveyman123** [comment] 2018-03-23 19:40
I passed in the file name to search-faces.js and nothing happens it just goes to the next line in the terminal.

here is my config for collectionId:

```
{
  "awsRegion":"us-east-1",
  "s3Bucket":"daveyman123",
  "lexVoiceId":"justin",
  "awsFaceCollection":"raspifacecollection"
}

```

1.searching
(node:1866) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
2.searching
error in searchFacesByImage { ResourceNotFoundException: The collection id: raspifacecollection does not exist

**Comment by daveyman123** [comment] 2018-03-23 20:10
it seems there may be an error because I dont have all the correct modules installed for creating a collection?

**Comment by just4give** [comment] 2018-03-23 23:37
Can you please execute this ? https://github.com/just4give/raspi-image-server/blob/master/create-collection.js  ... this will create the collection and then test again 
```
node create-collection.js
```

**Comment by daveyman123** [comment] 2018-03-23 23:42
Ok I will pull it down and do that

**Comment by daveyman123** [comment] 2018-03-23 23:48
I think I'm making progress now thank you!

**Comment by daveyman123** [comment] 2018-03-23 23:52
I think my mic is bad because it just asks me to repeat my name over and over.

**Comment by daveyman123** [comment] 2018-03-23 23:54
oh i think i have to say "my name is David"

**Comment by just4give** [comment] 2018-03-23 23:55
Be very close to the mic and say "my name is XXX" very loud...that might help

**Comment by daveyman123** [comment] 2018-03-24 00:01
hmm.. maybe we can try some more tomorrow. because its just asking me to repeat and the server hangs on "2.searching"

Thanks either way. feels good to get one step closer.

**Comment by just4give** [comment] 2018-03-24 00:07
check your cloud watch log for lambda function... after search is done, it sends the response back to lambda

**Comment by daveyman123** [comment] 2018-03-24 00:13
here is the most recent lambda log:
https://gyazo.com/6488115fa53876e996ecd555851b1b35
im not sure what to make of it.

here is the console log
uploaded image to s3 bucket: 1521849891803.jpg
1.searching
(node:3205) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
2.searching

**Comment by daveyman123** [comment] 2018-03-24 00:17
maybe i need to create a dynamo database?

**Comment by just4give** [comment] 2018-03-24 00:25
Your image-server is all set. While looking at your cloud watch log, I noticed search index returned call back to lambda saying it could not find any matching. That's all about image server's responsibility. Then lambda sends a response to lex which asks "What's your name". When you say "My name is David" , it calls NameIntent of the lambda ( saw that in log ) 
https://github.com/just4give/raspi-dexter-lambda/blob/master/handler.js#L124

But I noticed a SyntaxError ... you need to put some console.log inside handler.js and identify which step is failing ..code is fairly simple ... it index the image with the name you say , sing s3 url and send text ..you need to have SNS topic ... you don't need any dynamo ...

**Comment by daveyman123** [comment] 2018-03-24 00:33
Ok ok got to go to work now (call center calls). Will work on it again
later.

Thanks again

**Comment by daveyman123** [comment] 2018-03-24 12:44
I think it has something to do with the aws rekognition and s3 bucket being in different regions
I am getting this error when running test-search-faces.js:
 `message: 'Unable to get object metadata from S3. Check object key, region and/or access permissions.',
`
http://devans.mycanadapayday.com/aws-rekognition-unable-to-get-image-metadata-from-s3-check-object-key-region-andor-access-permissions/

I am not sure how to check the region of my Rekognition but I'm pretty sure it needs to be in the same region as my s3 bucket (us-east-1)

**Comment by just4give** [comment] 2018-03-24 14:45
Are u runnint test-search-faces.js on your pi? It will use the region you defined in config.json... please check the name (https://github.com/just4give/raspi-image-server/blob/master/test-search-faces.js#L17) you are passing is the jpg which is uploaded in your s3 bucket.

**Comment by daveyman123** [comment] 2018-03-24 15:02
I dont think its an issue with the image. The "test-search-faces.js" script times out almost immediately with the error i listed above. region is set to us-east-1 in the config file. which is the region of my s3 bucket

**Comment by just4give** [comment] 2018-03-24 15:04
So you confirmed the s3 key you are passing is legit ? I mean you have an image with that key in the bucket you specified ?

**Comment by daveyman123** [comment] 2018-03-24 15:19
Ok I think you are right. I wasnt giving the correct key for the image in the bucket. I changed it and test-search-faces passed

do i need to give any special parameters to the NameIntent in the bot on aws console? because now when i run the server it asks me to repeat when I say "My name is David"

**Comment by daveyman123** [comment] 2018-03-24 16:11
here is the logs from cloud watch:
https://gyazo.com/f4efb122312b4bd10e818164a3df38b0

I tried to add some console.logs but sometimes it messes up the program. Im not exactly sure where to put "console.log" in the code

**Comment by just4give** [comment] 2018-03-24 16:44
Great ! I think you are almost all set for end to end test....

**Comment by daveyman123** [comment] 2018-03-24 16:48
I tried an end to end test but its still getting caught up here:
uploaded image to s3 bucket: 1521904866316.jpg
1.searching
(node:2934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
2.searching

where should i put console.log in the lambda?

**Comment by just4give** [comment] 2018-03-24 16:51
your image process successfully sent the response to lambda. You can see lambda printed the response with status unmatched. And I believe it asked for name. What happened after that? I don't see in the log.

**Comment by daveyman123** [comment] 2018-03-24 16:53
it asks "could you repeat that" when I say "My name is David"

**Comment by just4give** [comment] 2018-03-24 16:56
be loud and say my name is david... make sure there is no background noise... it's a problem as we are using cheap mic

**Comment by daveyman123** [comment] 2018-03-24 16:58
yes I switched over to using a USB headset and that solved the problems of getting to the NameIntent using the intent "Hello" and "whats up". However it seems to be something else causing the problem this time.

the server gives this output:
1.searching
(node:2934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
2.searching

**Comment by just4give** [comment] 2018-03-24 17:00
as I said , your image server is good now...sending response back to lambda...you need to debug your lambda function....

**Comment by daveyman123** [comment] 2018-03-24 17:01
yes ok, where do I add console.log?
```
//      console.log
        switch (intentName) {
          case 'HelloIntent':
                  request(
                    {
//                    console.log
                      url : process.env.URL_CAPTURE,
                      method:'POST',
                      headers : {
                      "Authorization" : "Basic " + new Buffer( "raspi:secret").$
                    }
                    },
//                  console.log
                    function (error, response, body) {

                        if(error){
                          callback(error);
                        }else{
                          body = JSON.parse(body);

```

**Comment by just4give** [comment] 2018-03-25 01:33
Look at NameIntent

**Comment by daveyman123** [comment] 2018-03-25 01:56
I should put console.log somewhere in here.. in order to debug?
On my raspberry pi I have changed the topicarn.
```
 case 'NameIntent':
                    var name = event.currentIntent.slots.name;
                    var key = event.sessionAttributes.key;
                    var params = {
                        "CollectionId": config.awsFaceCollection,
                        "DetectionAttributes": [ "ALL" ],
                        "ExternalImageId": name,
                        "Image": {
                          "S3Object": {
                             "Bucket": config.s3Bucket,
                             "Name": key
                          }
                        }
                      }

                    rekognition.indexFaces(params, function(err, data) {
                        if (err) {
                          console.log(err, err.stack);
                        }else{
                          //console.log(data);

                          const url = s3.getSignedUrl('getObject', {
                              Bucket: config.s3Bucket,
                              Key: key,
                              Expires: 300
                          })

                          //console.log(url)

                          sns.publish({
                            Message: 'I stored face of '+ name+' . See the image I loaded in my brain. Link will expire in 5 minutes. ' + url,
                            TopicArn: 'arn:aws:sns:us-east-1:027378352884:raspiFaceTextMessage'
                          }, function (err, data) {
                            if(err){
                              console.log("error", err);
                            }else{
                              console.log('success',data);
                            }

                          });

                          callback(null,{
                              sessionAttributes: {key: key},
                              dialogAction: {
                                  type: 'Close',
                                  fulfillmentState:'Fulfilled',
                                  message:{
                                      contentType: 'PlainText',
                                      content: "I stored your picture "+name+" . Have a nice day!"
                                  }

                              },
                          })
                        }

                    });

              break;
```

**Comment by just4give** [comment] 2018-03-25 02:11
It's upto you how you want to debug your program. It would be very difficult for me to guide you without seeing what's happening runtime. I can suggest to put a console log before calling rekognition.indexFaces and print the name & s3 key. Check if those are correct.  Then put some console.log to make sure rekognition.indexFaces is successful or not.

**Comment by daveyman123** [comment] 2018-03-25 13:35
im confused about how to debug.
```
rekognition.indexFaces(params, function(err, data) {
                        console.log('Name':Name)
                        console.lgo('Bucket':Bucket)
```

**Comment by just4give** [comment] 2018-03-25 17:41
Seems you are not much familiar with nodejs :)  Try to replace this code. I added some console logs. You should see one after one in cloud watch. If you see console.log('5. sending response back to Lex'); getting printed then all went well. 
```
case 'NameIntent':
                    var name = event.currentIntent.slots.name;
                    var key = event.sessionAttributes.key;
                    var params = {
                        "CollectionId": config.awsFaceCollection,
                        "DetectionAttributes": [ "ALL" ],
                        "ExternalImageId": name,
                        "Image": {
                          "S3Object": {
                             "Bucket": config.s3Bucket,
                             "Name": key
                          }
                        }
                      }
                    console.log('1. name', name);
                    console.log('2. s3 key', key);
                    rekognition.indexFaces(params, function(err, data) {
                        if (err) {
                          console.log(err, err.stack);
                        }else{
                          //console.log(data);
                          console.log('3. Face indexed successfully');
                          const url = s3.getSignedUrl('getObject', {
                              Bucket: config.s3Bucket,
                              Key: key,
                              Expires: 300
                          })

                          console.log('4. s3 signed url',url);

                          sns.publish({
                            Message: 'I stored face of '+ name+' . See the image I loaded in my brain. Link will expire in 5 minutes. ' + url,
                            TopicArn: 'arn:aws:sns:us-east-1:027378352884:raspiFaceTextMessage'
                          }, function (err, data) {
                            if(err){
                              console.log("4.1 error", err);
                            }else{
                              console.log('4.1 success',data);
                            }

                          });

                          console.log('5. sending response back to Lex');
                          callback(null,{
                              sessionAttributes: {key: key},
                              dialogAction: {
                                  type: 'Close',
                                  fulfillmentState:'Fulfilled',
                                  message:{
                                      contentType: 'PlainText',
                                      content: "I stored your picture "+name+" . Have a nice day!"
                                  }

                              },
                          })
                        }

                    });

              break;
```

**Comment by daveyman123** [comment] 2018-03-25 19:31
I put in all the logs and here is the cloudwatch:
https://gyazo.com/53ad2e78f90ba38579bddb6a3980867f

It must be getting stuck before the logs?

**Comment by just4give** [comment] 2018-03-26 01:45
Your bot must have said "We never met before. What's your name" and waiting for your response..you need to say "My name is David" which will map invoke the Lex Bot and fire NameIntent.

**Comment by daveyman123** [comment] 2018-03-26 12:28
yes this is where its getting stuck. I give it a clear message of "My name is David" but it just keeps asking me to repeat.

**Comment by just4give** [comment] 2018-03-26 13:35
raspi-dexter-lex-ai creates a file request.wav ( your voice command) and sends to Lex bot. Go inside respi-dexter-lex-ai folder and find the file and then play to listen what has been captured and sent to Lex
```
aplay request.wav
```

**Comment by daveyman123** [comment] 2018-03-26 14:06
It looks like it must not be getting recorded. because there is no request.wav in raspi-dexter-lex-ai. Does it get after being used?

There is a request.wav in snowboy/rpi-arm-raspbian-8.0-1.2.0/
However, this request.wav appears to be empty. There is a temp.wav that plays for a while with no sound.

maybe I set the project folder up wrong?

**Comment by just4give** [comment] 2018-03-26 15:10
Comment this line (https://github.com/just4give/raspi-dexter-lex-ai/blob/master/bot.js#L47) ...this should keep the file.

**Comment by daveyman123** [comment] 2018-03-26 15:31
This leaves response.mpeg but not request.wav. If I comment out this line (https://github.com/just4give/raspi-dexter-lex-ai/blob/master/bot.js#L67) the request file is there. however it seems to be empty or very very short in length

**Comment by just4give** [comment] 2018-03-26 15:49
My bad ...I meant L67. If this file is empty that means , recording was not done properly when you said "My name is David" and that's the reason Bot asks you to repeat. I would suggest you change the Lex utterance to something else and say that ... check the recorded file ... it has to capture what you are saying ...

**Comment by daveyman123** [comment] 2018-03-26 16:26
Ok I am able to play back request.wav and it comes in loud and clear "My name is David"

I am having trouble finding in the code where the "My name is ______", is located.

**Comment by just4give** [comment] 2018-03-26 19:07
It's not in the code..take a look at your lex bot utterances under NameIntent. Lex will match the voice and call your lambda passing the intent name. Then your lambda ( case 'NameIntent' ) will fulfill the request. 

![image](https://user-images.githubusercontent.com/9275193/37927132-35f1d626-3107-11e8-84ef-a019903788b8.png)

**Comment by daveyman123** [comment] 2018-03-26 19:47
Omg its finally working!

**Comment by just4give** [comment] 2018-03-26 20:36
Awesome! Time for you to take a break :)

**Comment by just4give** [comment] 2018-03-26 20:37
It seems a very small project but lots of moving parts and integration. It was hard to debug remotely. I am glad were able to connect all the dots and got it working.

**Closed as completed** 2018-03-27 01:17 UTC
